steps:
  # 1. Build Docker image untuk frontend statis
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-frontend", "."]
    # asumsikan Dockerfile dan source ada di root folder build (kalau beda, bisa pakai dir:)

  # 2. Push image ke Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/my-frontend"]

  # 3. Deploy ke Cloud Ru`n
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "my-frontend",
        "--image",
        "gcr.io/$PROJECT_ID/my-frontend",
        "--timeout",
        "300s",
        "--port",
        "80",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
